name: conferer-snap
version: 1.0.0.0
synopsis: |
  conferer's FromConfig instances for snap Config
description: |
  Library to abstract the parsing of many haskell config values from different config sources

# _common/lib: !include ../../utils/package.common.yaml

# <<: *everything

library:
  source-dirs: src

homepage: https://conferer.ludat.io
category: Configuration
bug-reports: https://github.com/ludat/conferer/issues

extra-doc-files:
  - README.md
  - CHANGELOG.md
  - LICENSE

author: Lucas David Traverso
maintainer: lucas6246@gmail.com

copyright: (c) 2020 Lucas David Traverso
license: MPL-2.0
license-file: LICENSE

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - QuasiQuotes
  - ScopedTypeVariables
  - RecordWildCards
  - StrictData

ghc-options:
  - -Wall
  - -Wredundant-constraints
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
when:
  condition: impl(ghc >= 8.4.1)
  ghc-options:
    - -Wpartial-fields


dependencies:
  - base >= 4.3 && < 5
  - conferer >= 1.1.0.0 && < 2.0.0.0
  - text >= 1.1 && < 1.3
  - snap-server >= 1.0 && < 2.0
  - snap-core >= 1.0 && < 2.0

tests:
  specs:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - conferer-snap
    - hspec
